#! /bin/sh

source ./ipsec-xfrm

log() {
	echo "$@"
}

ebegin() {
	log "ebegin: $@"
}

eerror() {
	log "eerror: $@"
}

eend() {
	return $1
}

restart() {
	stop
	start
}

run() {
	if [ $1 == "start" ]; then
		log "Staring IPsec ... "
		start
	elif [ $1 == "update" ]; then
		log "Updating IPsec ..."
		update
	elif [ $1 == "stop" ]; then
		log "Stopping IPsec ..."
		stop
	elif [ $1 == "restart" ]; then
		log "Restarting IPsec ..."
		restart
	else
		echo "$1 - invalid command"
		log "$1 - invalid command"
	fi
}

run $1
