#! /bin/sh

PROG_DIR=${PROG_DIR:-"$(realpath $(dirname "${0}"))"}

source "${PROG_DIR}/ipsec-xfrm"

log() {
	echo "$@"
}

ebegin() {
	log "ebegin: $@"
}

eerror() {
	log "eerror: $@"
}

eend() {
	return $1
}

restart() {
	stop
	start
}

run() {
	case "${1}"
	in
		start|stop|restart|update|flush)
			log "IPsec ${1} ..."
			${1}
		;;

		*) eerror "Invalid command: ${1}" ;;
	esac
}

run $1
