#! /bin/sh

set -e

umask 077

IPSEC_DIR='/var/lib/ipsec'

# End the path with '/' if you sync a directory. (See rsync(1) for more information.
# The SYNC_PATH MUST differ from IPSEC_HOSTS_UPDATE and IPSEC_HOSTS_STABLE!
SYNC_PATH="${IPSEC_DIR}/update/ipsechosts-sync"
SYNC_FROM="${SYNC_PATH}"

mkdir -p "$(dirname ${SYNC_PATH})"

IPSEC_HOSTS_STABLE="${IPSEC_DIR}/ipsechosts"
IPSEC_HOSTS_UPDATE="${IPSEC_DIR}/ipsechosts-update"

if [ "${SYNC_PATH}" == "${IPSEC_HOSTS_STABLE}" -o "${SYNC_PATH}" == "${IPSEC_HOSTS_UPDATE}" ]
then
	echo "SYNC_PATH MUST differ from IPSEC_HOSTS_UPDATE and IPSEC_HOSTS_STABLE!" >&2
	exit 2
fi

rsync -togurz --delete "rsync://sync.virusfree.cz${SYNC_FROM}" "${SYNC_PATH}"
find "${SYNC_PATH}" -type f -print0 \
| xargs -0n1 sh -c 'echo "# data from file $0"; cat $0; echo' \
> ${IPSEC_HOSTS_UPDATE}

set +e

cmp "${IPSEC_HOSTS_STABLE}" "${IPSEC_HOSTS_UPDATE}"
if [[ $? == 1 ]]
then
	# Uncomment following line if you want to use this in conjunction with
	# SystemD, but do not forget to comment or remove the next one!

	# SystemD:
	#/usr/local/bin/ipsec update

	# OpenRC:
	rc-service ipsec-xfrm update
elif [[ $? == 2 ]]
then
	exit $?
fi
