#!/bin/sh
RSYNC="/usr/bin/rsync"
OPTS=""
#SRC="rsync://sync.virusfree.cz/var/lib/ipsec/ipsechosts-update"
SRC=/root/ipsechosts-update
DST="/var/lib/ipsec/ipsechosts-update"

${RSYNC} ${OPTS} ${SRC} ${DST} || return 1
cmp /var/lib/ipsec/ipsechosts ${SRC}
if ! [ $? -eq 0 ]; then
	/etc/init.d/ipsec update
	if [$? -eq 0 ]; then
		cp ${DST} /var/lib/ipsec/ipsechosts
	else
		/etc/init.d/ipsec restart
	fi
fi
exit 0
