#! /bin/sh

set -e

umask 077

IPSEC_DIR='/var/lib/ipsec'

SYNC_PATH="${IPSEC_DIR}/update/"
SYNC_FROM="${SYNC_PATH}"

IPSEC_HOSTS_STABLE="${IPSEC_DIR}/ipsechosts"
IPSEC_HOSTS_UPDATE="${IPSEC_DIR}/ipsechosts-update"

rsync -tpogurz --delete "rsync://sync.virusfree.cz${SYNC_FROM}" "${SYNC_PATH}"
find "${SYNC_PATH}" -type f -print0 \
| xargs -0n1 sh -c 'echo "# data from file $0"; cat $0; echo' \
> ${IPSEC_HOSTS_UPDATE}

set +e

cmp "${IPSEC_HOSTS_STABLE}" "${IPSEC_HOSTS_UPDATE}"
if [[ $? == 1 ]]
then
	/etc/init.d/ipsec-xfrm update
elif [[ $? == 2 ]]
then
	exit $?
fi
